export const books = [
  {
    id: 1,
    title: "Pride & Prejudice",
    author: "Jane Austen",
    cover: "https://picsum.photos/200/300?random=1",
    year: 1813,
    genre: "Historical Romance",
    description: "A witty exploration of love, class, and pride in Regency England.",
  },
  {
    id: 2,
    title: "Romeo & Juliet",
    author: "William Shakespeare",
    cover: "https://picsum.photos/200/300?random=2",
    year: 1597,
    genre: "Tragic Romance",
    description: "A timeless tale of star-crossed lovers whose passion defies family rivalries.",
  },
  {
    id: 3,
    title: "The Notebook",
    author: "Nicholas Sparks",
    cover: "https://picsum.photos/200/300?random=3",
    year: 1996,
    genre: "Contemporary Romance",
    description: "A sweeping love story of Noah and Allie, tested by time and circumstance.",
  },
  {
    id: 4,
    title: "Outlander",
    author: "Diana Gabaldon",
    cover: "https://picsum.photos/200/300?random=4",
    year: 1991,
    genre: "Historical Fantasy Romance",
    description: "A WWII nurse is transported back to 18th-century Scotland and meets a warrior.",
  },
  {
    id: 5,
    title: "Me Before You",
    author: "Jojo Moyes",
    cover: "https://picsum.photos/200/300?random=5",
    year: 2012,
    genre: "Drama Romance",
    description: "An emotional love story between Louisa, a quirky caregiver, and Will, a former adventurer.",
  },
  {
    id: 6,
    title: "Twilight",
    author: "Stephenie Meyer",
    cover: "https://picsum.photos/200/300?random=6",
    year: 2005,
    genre: "Paranormal Romance",
    description: "The story of Bella and Edward, a forbidden love between a human and a vampire.",
  },
  {
    id: 7,
    title: "Bridgerton: The Duke and I",
    author: "Julia Quinn",
    cover: "https://picsum.photos/200/300?random=7",
    year: 2000,
    genre: "Regency Romance",
    description: "Daphne Bridgerton strikes a deal with the Duke of Hastings that turns into true love.",
  },
  {
    id: 8,
    title: "Jane Eyre",
    author: "Charlotte Brontë",
    cover: "https://picsum.photos/200/300?random=8",
    year: 1847,
    genre: "Gothic Romance",
    description: "A young governess falls in love with her brooding employer, hiding a dark secret.",
  },
  {
    id: 9,
    title: "Gone with the Wind",
    author: "Margaret Mitchell",
    cover: "https://picsum.photos/200/300?random=9",
    year: 1936,
    genre: "Historical Romance",
    description: "Scarlett O'Hara navigates love and survival during the American Civil War.",
  },
  {
    id: 10,
    title: "Anna Karenina",
    author: "Leo Tolstoy",
    cover: "https://picsum.photos/200/300?random=10",
    year: 1877,
    genre: "Classic Romance",
    description: "A tragic love affair challenges societal norms in Imperial Russia.",
  },
  {
    id: 11,
    title: "Rebecca",
    author: "Daphne du Maurier",
    cover: "https://picsum.photos/200/300?random=11",
    year: 1938,
    genre: "Romantic Suspense",
    description: "A young bride is haunted by her husband’s late wife in the mysterious Manderley estate.",
  },
  {
    id: 12,
    title: "The Time Traveler’s Wife",
    author: "Audrey Niffenegger",
    cover: "https://picsum.photos/200/300?random=12",
    year: 2003,
    genre: "Sci-Fi Romance",
    description: "A love story disrupted by uncontrollable time travel.",
  },
  {
    id: 13,
    title: "Persuasion",
    author: "Jane Austen",
    cover: "https://picsum.photos/200/300?random=13",
    year: 1817,
    genre: "Historical Romance",
    description: "Anne Elliot rekindles her romance with a naval captain years after breaking his heart.",
  },
  {
    id: 14,
    title: "Call Me by Your Name",
    author: "André Aciman",
    cover: "https://picsum.photos/200/300?random=14",
    year: 2007,
    genre: "Coming-of-Age Romance",
    description: "A passionate summer romance blossoms in the Italian countryside.",
  },
  {
    id: 15,
    title: "Wuthering Heights",
    author: "Emily Brontë",
    cover: "https://picsum.photos/200/300?random=15",
    year: 1847,
    genre: "Gothic Romance",
    description: "A dark and stormy love between Heathcliff and Catherine across generations.",
  },
  {
    id: 16,
    title: "The Fault in Our Stars",
    author: "John Green",
    cover: "https://picsum.photos/200/300?random=16",
    year: 2012,
    genre: "Young Adult Romance",
    description: "Two teenagers with cancer embark on a moving journey of love and loss.",
  },
  {
    id: 17,
    title: "A Walk to Remember",
    author: "Nicholas Sparks",
    cover: "https://picsum.photos/200/300?random=17",
    year: 1999,
    genre: "Drama Romance",
    description: "A rebellious teen falls in love with a gentle minister’s daughter.",
  },
  {
    id: 18,
    title: "Eleanor & Park",
    author: "Rainbow Rowell",
    cover: "https://picsum.photos/200/300?random=18",
    year: 2013,
    genre: "Young Adult Romance",
    description: "Two misfit teens find love through mixtapes and shared bus rides.",
  },
  {
    id: 19,
    title: "Beautiful Disaster",
    author: "Jamie McGuire",
    cover: "https://picsum.photos/200/300?random=19",
    year: 2011,
    genre: "New Adult Romance",
    description: "A good girl and a notorious bad boy enter a dangerous love game.",
  },
  {
    id: 20,
    title: "Love in the Time of Cholera",
    author: "Gabriel García Márquez",
    cover: "https://picsum.photos/200/300?random=20",
    year: 1985,
    genre: "Magical Realism Romance",
    description: "Florentino waits decades to reunite with his first love, Fermina.",
  },
  {
    id: 21,
    title: "Fifty Shades of Grey",
    author: "E. L. James",
    cover: "https://picsum.photos/200/300?random=21",
    year: 2011,
    genre: "Erotic Romance",
    description: "The intense and controversial romance between Anastasia Steele and Christian Grey.",
  },
  {
    id: 22,
    title: "Red, White & Royal Blue",
    author: "Casey McQuiston",
    cover: "https://picsum.photos/200/300?random=22",
    year: 2019,
    genre: "LGBTQ+ Romance",
    description: "The First Son of the United States falls for a British prince.",
  },
  {
    id: 23,
    title: "The Rosie Project",
    author: "Graeme Simsion",
    cover: "https://picsum.photos/200/300?random=23",
    year: 2013,
    genre: "Romantic Comedy",
    description: "A genetics professor uses science to find a wife but ends up with love instead.",
  },
  {
    id: 24,
    title: "One Day",
    author: "David Nicholls",
    cover: "https://picsum.photos/200/300?random=24",
    year: 2009,
    genre: "Drama Romance",
    description: "Dexter and Emma meet every year on the same date, capturing life’s changes and love.",
  },
  {
    id: 25,
    title: "It Ends with Us",
    author: "Colleen Hoover",
    cover: "https://picsum.photos/200/300?random=25",
    year: 2016,
    genre: "Contemporary Romance",
    description: "A deeply emotional story about love, resilience, and breaking cycles of abuse.",
  },
  {
    id: 26,
    title: "To All the Boys I’ve Loved Before",
    author: "Jenny Han",
    cover: "https://picsum.photos/200/300?random=26",
    year: 2014,
    genre: "Young Adult Romance",
    description: "Lara Jean’s secret love letters accidentally get sent out to her crushes.",
  },
  {
    id: 27,
    title: "The Hating Game",
    author: "Sally Thorne",
    cover: "https://picsum.photos/200/300?random=27",
    year: 2016,
    genre: "Romantic Comedy",
    description: "Coworkers Lucy and Joshua turn office rivalry into sizzling chemistry.",
  },
]